[project]
name = "gh-mage"
version = "0.1.0"
description = "tiny ai agent project to help do github better"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.0.1",
]
